### PR TITLE
feat: host add domain support

### PR DESCRIPTION
**Pull request by minquiers**

### CODE REVIEW

**Comment by vran-dev** [comment]
@minquiers 

Thanks for your contribution, would you explain why you do this modification? 

such as  you want to solve some problem or add new feature.

**Comment by minquiers** [comment]
add new feature . Zookeeper in A Chinese home does not have a fixed public IP address and can only use DDNS. Therefore, host must support the domain name

**Comment by minquiers** [comment]
> @minquiers
> 
> Thanks for your contribution, would you explain why you do this modification?
> 
> such as you want to solve some problem or add new feature.

Zookeeper in A Chinese home does not have a fixed public IP address and can only use DDNS. Therefore, host must support the domain name

**Comment by vran-dev** [comment]
Sorry for taking so long to reply to you

prettyzoo actually supports connecting to zookeeper through a domain name

**Pull request closed without merging**
